"""Generate data/wands.json: 11 schools x 5 = 55 wands (keeps basic_wand).

Usage: python tools/scripts/gen_wands.py
Output: data/wands.json (UTF-8, indent=2)
"""
import json
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
WANDS_PATH = os.path.join(ROOT, "data", "wands.json")

EXISTING = [
    {
        "id": "basic_wand", "name": "学徒法杖", "rarity": "common", "price": 140,
        "shape": "none", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {},
        "shape_mods": {},
        "description": "基础法杖：无特殊形态，法术按原样释放",
        "icon": "res://assets/icons/willibab/STAFFS_0.png", "school": "melee",
    },
    {
        "id": "fire_staff", "name": "烈焰法杖", "rarity": "common", "price": 225,
        "shape": "burst", "damage_mult": 1.15, "cd_mult": 1.0, "element_bonus": {"fire": 0.25},
        "shape_mods": {"aoe_mult": 1.8},
        "description": "爆发形态：所有法术爆炸范围 +80%，火系伤害 +25%",
        "icon": "res://assets/icons/willibab/STAFFS_1.png", "school": "fire",
    },
    {
        "id": "rapid_staff", "name": "连珠法杖", "rarity": "common", "price": 250,
        "shape": "rapid", "damage_mult": 0.9, "cd_mult": 0.72, "element_bonus": {},
        "shape_mods": {"shots": 3, "damage_mult": 0.8},
        "description": "连珠形态：法术三连发（单发 80% 伤害），冷却 -28%",
        "icon": "res://assets/icons/willibab/STAFFS_2.png", "school": "wind",
    },
    {
        "id": "orbit_staff", "name": "环绕法杖", "rarity": "rare", "price": 420,
        "shape": "orbit", "damage_mult": 0.85, "cd_mult": 0.8, "element_bonus": {},
        "shape_mods": {"orbit": 2, "damage_mult": 0.8},
        "description": "环绕形态：法术环绕自身持续输出，冷却 -20%",
        "icon": "res://assets/icons/willibab/STAFFS_3.png", "school": "water",
    },
    {
        "id": "scatter_staff", "name": "散射法杖", "rarity": "rare", "price": 390,
        "shape": "scatter", "damage_mult": 0.95, "cd_mult": 0.9, "element_bonus": {},
        "shape_mods": {"shots": 5, "spread_angle": 24.0, "damage_mult": 0.7},
        "description": "散射形态：法术扇形五连射",
        "icon": "res://assets/icons/willibab/STAFFS_4.png", "school": "fire",
    },
    {
        "id": "frost_staff", "name": "霜冻法杖", "rarity": "rare", "price": 450,
        "shape": "frost", "damage_mult": 1.0, "cd_mult": 1.0,
        "element_bonus": {"ice": 0.4, "water": 0.3},
        "shape_mods": {"slow_power": 1.8},
        "description": "霜冻形态：冰/水伤害 +40%/+30%，减速效果大幅增强",
        "icon": "res://assets/icons/willibab/STAFFS_5.png", "school": "ice",
    },
    {
        "id": "ice_staff", "name": "冰锥法杖", "rarity": "rare", "price": 450,
        "shape": "pierce", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"ice": 0.35},
        "shape_mods": {"pierce": 2, "speed_mult": 1.25},
        "description": "冰锥形态：弹道贯穿 2 个敌人，弹速 +25%，冰系伤害 +35%",
        "icon": "res://assets/icons/willibab/STAFFS_8.png", "school": "ice",
    },
    {
        "id": "poison_staff", "name": "毒雾法杖", "rarity": "rare", "price": 450,
        "shape": "poison", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"poison": 0.5},
        "shape_mods": {"aoe_mult": 2.0, "delay": 0.4},
        "description": "毒雾形态：范围 +100%，延迟 0.4 秒引爆，毒系伤害 +50%",
        "icon": "res://assets/icons/willibab/STAFFS_9.png", "school": "poison",
    },
    {
        "id": "light_staff", "name": "圣光法杖", "rarity": "rare", "price": 450,
        "shape": "light", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"light": 0.4},
        "shape_mods": {"drain": 0.06},
        "description": "圣光形态：命中回复 6% 伤害值的生命，光系伤害 +40%",
        "icon": "res://assets/icons/willibab/STAFFS_10.png", "school": "defense",
    },
    {
        "id": "thunder_staff", "name": "雷霆法杖", "rarity": "legendary", "price": 720,
        "shape": "chain", "damage_mult": 1.0, "cd_mult": 1.0,
        "element_bonus": {"lightning": 0.5},
        "shape_mods": {"pierce": 3, "speed_mult": 1.3},
        "description": "雷霆形态：弹道贯穿 3 个敌人，弹速 +30%，雷系伤害 +50%",
        "icon": "res://assets/icons/willibab/STAFFS_6.png", "school": "lightning",
    },
    {
        "id": "void_staff", "name": "虚空法杖", "rarity": "legendary", "price": 740,
        "shape": "split", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"void": 0.45},
        "shape_mods": {"split": 3, "aoe_mult": 1.6},
        "description": "虚空形态：命中分裂 3 枚小弹，范围 +60%，虚空伤害 +45%",
        "icon": "res://assets/icons/willibab/STAFFS_11.png", "school": "curse",
    },
    {
        "id": "bounce_staff", "name": "弹射法杖", "rarity": "rare", "price": 450,
        "shape": "bounce", "damage_mult": 1.15, "cd_mult": 1.0, "element_bonus": {},
        "shape_mods": {"bounce": 2, "damage_mult": 1.15},
        "description": "弹射形态：弹道碰壁反弹 2 次，伤害 +15%",
        "icon": "res://assets/icons/willibab/STAFFS_12.png", "school": "wind",
    },
    {
        "id": "summon_staff", "name": "唤灵法杖", "rarity": "legendary", "price": 750,
        "shape": "summon", "damage_mult": 1.1, "cd_mult": 0.85, "element_bonus": {"summon": 0.5},
        "shape_mods": {},
        "description": "唤灵形态：召唤系伤害 +50%，冷却 -15%，召唤物上限 +1",
        "icon": "res://assets/icons/willibab/STAFFS_7.png", "school": "summon",
    },
]

NEW = [
    {"id": "lava_staff", "name": "熔岩法杖", "rarity": "common", "price": 260,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.05, "element_bonus": {"fire": 0.25},
     "shape_mods": {"aoe_mult": 1.5},
     "description": "爆发形态：法术范围 +50%，火系伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_13.png", "school": "fire"},
    {"id": "fire_rain_staff", "name": "火雨法杖", "rarity": "rare", "price": 480,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.05, "element_bonus": {"fire": 0.35},
     "shape_mods": {"aoe_mult": 1.6, "delay": 0.35},
     "description": "爆发形态：范围 +60%，落点延迟 0.35 秒，火系伤害 +35%",
     "icon": "res://assets/icons/willibab/STAFFS_14.png", "school": "fire"},
    {"id": "phoenix_staff", "name": "凤凰法杖", "rarity": "legendary", "price": 780,
     "shape": "burst", "damage_mult": 1.1, "cd_mult": 1.0, "element_bonus": {"fire": 0.45},
     "shape_mods": {"aoe_mult": 2.0, "drain": 0.05},
     "description": "爆发形态：范围 +100%，命中吸血 5%，火系伤害 +45%",
     "icon": "res://assets/icons/willibab/STAFFS_15.png", "school": "fire"},
    {"id": "shatter_staff", "name": "碎冰法杖", "rarity": "common", "price": 240,
     "shape": "pierce", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"ice": 0.25},
     "shape_mods": {"pierce": 1, "speed_mult": 1.15},
     "description": "贯穿形态：弹道贯穿 1 个敌人，弹速 +15%，冰系伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_16.png", "school": "ice"},
    {"id": "ice_orbit_staff", "name": "冰环法杖", "rarity": "rare", "price": 520,
     "shape": "orbit", "damage_mult": 0.9, "cd_mult": 0.85, "element_bonus": {"ice": 0.35},
     "shape_mods": {"orbit": 2, "damage_mult": 0.85},
     "description": "环绕形态：2 枚冰弹环绕持续输出，冷却 -15%，冰系伤害 +35%",
     "icon": "res://assets/icons/willibab/STAFFS_17.png", "school": "ice"},
    {"id": "arctic_staff", "name": "极寒法杖", "rarity": "legendary", "price": 760,
     "shape": "frost", "damage_mult": 1.05, "cd_mult": 1.0, "element_bonus": {"ice": 0.5},
     "shape_mods": {"aoe_mult": 1.8, "speed_mult": 1.2},
     "description": "霜冻形态：范围 +80%，弹速 +20%，冰系伤害 +50%",
     "icon": "res://assets/icons/willibab/STAFFS_18.png", "school": "ice"},
    {"id": "surge_staff", "name": "电涌法杖", "rarity": "common", "price": 230,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"lightning": 0.2},
     "shape_mods": {"aoe_mult": 1.3, "damage_mult": 1.15},
     "description": "爆发形态：范围 +30%，伤害 +15%，雷系伤害 +20%",
     "icon": "res://assets/icons/willibab/STAFFS_19.png", "school": "lightning"},
    {"id": "volt_staff", "name": "高压法杖", "rarity": "common", "price": 250,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"lightning": 0.25},
     "shape_mods": {"speed_mult": 1.3, "aoe_mult": 1.2},
     "description": "爆发形态：弹速 +30%，范围 +20%，雷系伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_20.png", "school": "lightning"},
    {"id": "storm_staff", "name": "雷云法杖", "rarity": "rare", "price": 480,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.05, "element_bonus": {"lightning": 0.35},
     "shape_mods": {"aoe_mult": 1.7, "delay": 0.3},
     "description": "爆发形态：范围 +70%，落点延迟 0.3 秒，雷系伤害 +35%",
     "icon": "res://assets/icons/willibab/STAFFS_21.png", "school": "lightning"},
    {"id": "chain_staff", "name": "连锁法杖", "rarity": "rare", "price": 550,
     "shape": "chain", "damage_mult": 1.05, "cd_mult": 1.0, "element_bonus": {"lightning": 0.4},
     "shape_mods": {"pierce": 2, "speed_mult": 1.2},
     "description": "雷霆形态：弹道贯穿 2 个敌人，弹速 +20%，雷系伤害 +40%",
     "icon": "res://assets/icons/willibab/STAFFS_22.png", "school": "lightning"},
    {"id": "corrosion_staff", "name": "腐蚀法杖", "rarity": "common", "price": 250,
     "shape": "poison", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"poison": 0.25},
     "shape_mods": {"aoe_mult": 1.4, "delay": 0.2},
     "description": "毒雾形态：范围 +40%，延迟 0.2 秒引爆，毒系伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_23.png", "school": "poison"},
    {"id": "venom_blade_staff", "name": "毒刃法杖", "rarity": "common", "price": 240,
     "shape": "pierce", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"poison": 0.25},
     "shape_mods": {"pierce": 1},
     "description": "贯穿形态：弹道贯穿 1 个敌人，毒系伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_24.png", "school": "poison"},
    {"id": "plague_staff", "name": "疫病法杖", "rarity": "rare", "price": 500,
     "shape": "poison", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"poison": 0.45},
     "shape_mods": {"aoe_mult": 1.8, "speed_mult": 0.9},
     "description": "毒雾形态：范围 +80%，毒系伤害 +45%",
     "icon": "res://assets/icons/willibab/STAFFS_25.png", "school": "poison"},
    {"id": "pestilence_staff", "name": "瘟疫法杖", "rarity": "legendary", "price": 790,
     "shape": "poison", "damage_mult": 1.1, "cd_mult": 0.95, "element_bonus": {"poison": 0.6},
     "shape_mods": {"aoe_mult": 2.2, "drain": 0.04},
     "description": "毒雾形态：范围 +120%，命中吸血 4%，毒系伤害 +60%",
     "icon": "res://assets/icons/willibab/STAFFS_26.png", "school": "poison"},
    {"id": "legion_staff", "name": "军团法杖", "rarity": "common", "price": 260,
     "shape": "summon", "damage_mult": 1.0, "cd_mult": 0.9, "element_bonus": {"summon": 0.25},
     "shape_mods": {},
     "description": "唤灵形态：召唤系伤害 +25%，冷却 -10%",
     "icon": "res://assets/icons/willibab/STAFFS_27.png", "school": "summon"},
    {"id": "death_rattle_staff", "name": "亡语法杖", "rarity": "common", "price": 250,
     "shape": "summon", "damage_mult": 1.05, "cd_mult": 0.95, "element_bonus": {"summon": 0.2},
     "shape_mods": {},
     "description": "唤灵形态：召唤系伤害 +20%，伤害 +5%",
     "icon": "res://assets/icons/willibab/STAFFS_28.png", "school": "summon"},
    {"id": "totem_staff", "name": "图腾法杖", "rarity": "rare", "price": 460,
     "shape": "summon", "damage_mult": 1.15, "cd_mult": 1.0, "element_bonus": {"summon": 0.35},
     "shape_mods": {},
     "description": "唤灵形态：召唤系伤害 +35%，伤害 +15%",
     "icon": "res://assets/icons/willibab/STAFFS_29.png", "school": "summon"},
    {"id": "pact_staff", "name": "契约法杖", "rarity": "rare", "price": 520,
     "shape": "summon", "damage_mult": 0.95, "cd_mult": 0.75, "element_bonus": {"summon": 0.3},
     "shape_mods": {},
     "description": "唤灵形态：召唤系伤害 +30%，冷却 -25%",
     "icon": "res://assets/icons/willibab/STAFFS_30.png", "school": "summon"},
    {"id": "water_bolt_staff", "name": "水弹法杖", "rarity": "common", "price": 240,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"water": 0.25},
     "shape_mods": {"aoe_mult": 1.3},
     "description": "爆发形态：范围 +30%，水系伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_31.png", "school": "water"},
    {"id": "tide_staff", "name": "潮汐法杖", "rarity": "rare", "price": 500,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"water": 0.4},
     "shape_mods": {"aoe_mult": 1.8, "speed_mult": 1.1},
     "description": "爆发形态：范围 +80%，弹速 +10%，水系伤害 +40%",
     "icon": "res://assets/icons/willibab/STAFFS_32.png", "school": "water"},
    {"id": "maelstrom_staff", "name": "漩涡法杖", "rarity": "rare", "price": 540,
     "shape": "orbit", "damage_mult": 0.9, "cd_mult": 0.9, "element_bonus": {"water": 0.35},
     "shape_mods": {"orbit": 3, "damage_mult": 0.8},
     "description": "环绕形态：3 枚水弹环绕持续输出，冷却 -10%，水系伤害 +35%",
     "icon": "res://assets/icons/willibab/STAFFS_33.png", "school": "water"},
    {"id": "abyss_staff", "name": "深水法杖", "rarity": "legendary", "price": 780,
     "shape": "scatter", "damage_mult": 1.0, "cd_mult": 0.95, "element_bonus": {"water": 0.5},
     "shape_mods": {"shots": 5, "spread_angle": 20.0, "damage_mult": 0.75},
     "description": "散射形态：扇形五连射，冷却 -5%，水系伤害 +50%",
     "icon": "res://assets/icons/willibab/STAFFS_34.png", "school": "water"},
    {"id": "gale_staff", "name": "疾风法杖", "rarity": "common", "price": 230,
     "shape": "none", "damage_mult": 0.95, "cd_mult": 1.0, "element_bonus": {},
     "shape_mods": {"speed_mult": 1.5},
     "description": "无形态：弹速 +50%，伤害 -5%",
     "icon": "res://assets/icons/willibab/STAFFS_35.png", "school": "wind"},
    {"id": "whirl_staff", "name": "回旋法杖", "rarity": "rare", "price": 500,
     "shape": "orbit", "damage_mult": 0.9, "cd_mult": 0.9, "element_bonus": {},
     "shape_mods": {"orbit": 2, "damage_mult": 0.85, "speed_mult": 1.15},
     "description": "环绕形态：2 枚弹环绕持续输出，弹速 +15%，冷却 -10%",
     "icon": "res://assets/icons/willibab/STAFFS_36.png", "school": "wind"},
    {"id": "tempest_staff", "name": "风暴法杖", "rarity": "legendary", "price": 800,
     "shape": "scatter", "damage_mult": 1.05, "cd_mult": 0.9, "element_bonus": {},
     "shape_mods": {"shots": 7, "spread_angle": 30.0, "damage_mult": 0.65},
     "description": "散射形态：扇形七连射，伤害 +5%，冷却 -10%",
     "icon": "res://assets/icons/willibab/STAFFS_37.png", "school": "wind"},
    {"id": "shield_staff", "name": "护盾法杖", "rarity": "common", "price": 240,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"light": 0.2},
     "shape_mods": {"aoe_mult": 1.5, "drain": 0.03},
     "description": "爆发形态：范围 +50%，命中吸血 3%，光系伤害 +20%",
     "icon": "res://assets/icons/willibab/STAFFS_38.png", "school": "defense"},
    {"id": "bedrock_staff", "name": "磐石法杖", "rarity": "common", "price": 250,
     "shape": "burst", "damage_mult": 1.05, "cd_mult": 1.0, "element_bonus": {"light": 0.2},
     "shape_mods": {"aoe_mult": 1.4},
     "description": "爆发形态：范围 +40%，伤害 +5%，光系伤害 +20%",
     "icon": "res://assets/icons/willibab/STAFFS_39.png", "school": "defense"},
    {"id": "thorn_staff", "name": "荆棘法杖", "rarity": "rare", "price": 480,
     "shape": "pierce", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"light": 0.3},
     "shape_mods": {"pierce": 2, "speed_mult": 1.1},
     "description": "贯穿形态：弹道贯穿 2 个敌人，弹速 +10%，光系伤害 +30%",
     "icon": "res://assets/icons/willibab/STAFFS_40.png", "school": "defense"},
    {"id": "aegis_staff", "name": "圣盾法杖", "rarity": "legendary", "price": 820,
     "shape": "burst", "damage_mult": 1.1, "cd_mult": 1.0, "element_bonus": {"light": 0.5},
     "shape_mods": {"aoe_mult": 2.0, "drain": 0.08},
     "description": "爆发形态：范围 +100%，命中吸血 8%，光系伤害 +50%",
     "icon": "res://assets/icons/willibab/STAFFS_41.png", "school": "defense"},
    {"id": "weaken_staff", "name": "虚弱法杖", "rarity": "common", "price": 250,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"void": 0.25},
     "shape_mods": {"aoe_mult": 1.4},
     "description": "爆发形态：范围 +40%，虚空伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_42.png", "school": "curse"},
    {"id": "slow_curse_staff", "name": "迟缓法杖", "rarity": "common", "price": 240,
     "shape": "scatter", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"void": 0.2},
     "shape_mods": {"shots": 4, "spread_angle": 20.0, "damage_mult": 0.8},
     "description": "散射形态：扇形四连射，虚空伤害 +20%",
     "icon": "res://assets/icons/willibab/STAFFS_43.png", "school": "curse"},
    {"id": "decay_staff", "name": "衰败法杖", "rarity": "rare", "price": 520,
     "shape": "burst", "damage_mult": 1.0, "cd_mult": 1.05, "element_bonus": {"void": 0.4},
     "shape_mods": {"aoe_mult": 1.7, "delay": 0.4},
     "description": "爆发形态：范围 +70%，落点延迟 0.4 秒，虚空伤害 +40%",
     "icon": "res://assets/icons/willibab/STAFFS_44.png", "school": "curse"},
    {"id": "dread_staff", "name": "恐慌法杖", "rarity": "rare", "price": 550,
     "shape": "split", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"void": 0.35},
     "shape_mods": {"split": 2, "damage_mult": 0.9},
     "description": "分裂形态：命中分裂 2 枚小弹，虚空伤害 +35%",
     "icon": "res://assets/icons/willibab/STAFFS_45.png", "school": "curse"},
    {"id": "keen_staff", "name": "锐利法杖", "rarity": "common", "price": 220,
     "shape": "pierce", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {},
     "shape_mods": {"pierce": 1, "speed_mult": 1.2},
     "description": "贯穿形态：弹道贯穿 1 个敌人，弹速 +20%",
     "icon": "res://assets/icons/willibab/STAFFS_46.png", "school": "crit"},
    {"id": "combo_staff", "name": "连击法杖", "rarity": "common", "price": 260,
     "shape": "rapid", "damage_mult": 0.95, "cd_mult": 0.8, "element_bonus": {},
     "shape_mods": {"shots": 3, "damage_mult": 0.8},
     "description": "连珠形态：法术三连发（单发 80% 伤害），冷却 -20%",
     "icon": "res://assets/icons/willibab/STAFFS_47.png", "school": "crit"},
    {"id": "deadly_staff", "name": "致命法杖", "rarity": "rare", "price": 520,
     "shape": "split", "damage_mult": 1.1, "cd_mult": 1.0, "element_bonus": {},
     "shape_mods": {"split": 2, "damage_mult": 0.95},
     "description": "分裂形态：命中分裂 2 枚小弹，伤害 +10%",
     "icon": "res://assets/icons/willibab/STAFFS_48.png", "school": "crit"},
    {"id": "weakpoint_staff", "name": "要害法杖", "rarity": "rare", "price": 480,
     "shape": "scatter", "damage_mult": 1.0, "cd_mult": 0.95, "element_bonus": {},
     "shape_mods": {"shots": 5, "spread_angle": 24.0, "damage_mult": 0.7},
     "description": "散射形态：扇形五连射，冷却 -5%",
     "icon": "res://assets/icons/willibab/STAFFS_49.png", "school": "crit"},
    {"id": "bloodblade_staff", "name": "血刃法杖", "rarity": "legendary", "price": 820,
     "shape": "pierce", "damage_mult": 1.15, "cd_mult": 1.0, "element_bonus": {},
     "shape_mods": {"pierce": 3, "drain": 0.07, "speed_mult": 1.2},
     "description": "贯穿形态：弹道贯穿 3 个敌人，命中吸血 7%，弹速 +20%",
     "icon": "res://assets/icons/willibab/STAFFS_50.png", "school": "crit"},
    {"id": "warblade_staff", "name": "战刃法杖", "rarity": "common", "price": 250,
     "shape": "pierce", "damage_mult": 1.0, "cd_mult": 1.0, "element_bonus": {"blade": 0.25},
     "shape_mods": {"pierce": 1},
     "description": "贯穿形态：弹道贯穿 1 个敌人，斩击伤害 +25%",
     "icon": "res://assets/icons/willibab/STAFFS_51.png", "school": "melee"},
    {"id": "charge_staff", "name": "突进法杖", "rarity": "common", "price": 230,
     "shape": "none", "damage_mult": 1.0, "cd_mult": 0.95, "element_bonus": {"blade": 0.2},
     "shape_mods": {"speed_mult": 1.4},
     "description": "无形态：弹速 +40%，冷却 -5%，斩击伤害 +20%",
     "icon": "res://assets/icons/willibab/STAFFS_52.png", "school": "melee"},
    {"id": "heavy_staff", "name": "重击法杖", "rarity": "rare", "price": 500,
     "shape": "burst", "damage_mult": 1.1, "cd_mult": 1.0, "element_bonus": {"blade": 0.35},
     "shape_mods": {"aoe_mult": 1.7},
     "description": "爆发形态：范围 +70%，伤害 +10%，斩击伤害 +35%",
     "icon": "res://assets/icons/willibab/STAFFS_53.png", "school": "melee"},
    {"id": "whirlblade_staff", "name": "旋风法杖", "rarity": "legendary", "price": 790,
     "shape": "orbit", "damage_mult": 0.95, "cd_mult": 0.9, "element_bonus": {"blade": 0.5},
     "shape_mods": {"orbit": 2, "damage_mult": 0.9},
     "description": "环绕形态：2 枚斩击环绕持续输出，冷却 -10%，斩击伤害 +50%",
     "icon": "res://assets/icons/willibab/STAFFS_54.png", "school": "melee"},
]


def main() -> None:
    wands = EXISTING + NEW
    ids = [w["id"] for w in wands]
    assert len(ids) == len(set(ids)), "duplicated id"
    assert len(wands) == 55, "expected 55, got %d" % len(wands)
    with open(WANDS_PATH, "w", encoding="utf-8") as f:
        json.dump({"wands": wands}, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("written:", WANDS_PATH, len(wands), "wands")


if __name__ == "__main__":
    main()
